env:
  es6: true
  node: true
extends: './index.js'
overrides:
  - env:
      jest: true
    files:
      - test/*.ts
      - test/**/*.ts
    rules:
      '@typescript-eslint/no-magic-numbers': off
      no-magic-numbers: 0
      unicorn/no-unsafe-regex: off
  - files:
      - scripts/**/*.ts
    rules:
      no-console: 0
  - files:
      - test/fixtures/**
    rules:
      unicorn/filename-case: off
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
