steps:
  - name: node:10
    id: dependencies
    entrypoint: npm
    args:
      - ci
  - name: node:10
    id: format
    waitFor:
      - dependencies
    entrypoint: npm
    args:
      - run
      - format
  - name: node:10
    id: authentication
    waitFor:
      - format
    entrypoint: sh
    args:
      - -c
      - 'echo //registry.npmjs.org/:_authToken=$${NPM_TOKEN} >> .npmrc'
    secretEnv:
      - NPM_TOKEN
  - name: node:10
    id: release
    waitFor:
      - authentication
    entrypoint: bash
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          npm publish || true
        fi
  - name: node:10
    id: release:dev
    waitFor:
      - release
    entrypoint: bash
    args:
      - '-c'
      - |
        npm version prerelease --preid="${SHORT_SHA}"
        npm publish --tag="dev"
secrets:
  - kmsKeyName: projects/com-ridedott-build/locations/global/keyRings/environments/cryptoKeys/production
    secretEnv:
      NPM_TOKEN: CiQAcJJb8yGCxE/zUPzZoj24vbEzbgEwXTta2YjmkzmAJc81y1gSTAB9H8yZucSd0nGHr7yoz2UUbv8HTdhaiLc9zD78VbiwuehG2f0xj7lq4vLOolMtqtN+elBdLjJ15c8uLouB3uDpqL0VQHYX0HncWrs=
