steps:
  - name: node:10
    id: dependencies
    entrypoint: npm
    args:
      - ci
  - name: node:10
    id: format
    waitFor:
      - dependencies
    entrypoint: npm
    args:
      - run
      - format
  - name: node:10
    id: authentication
    waitFor:
      - format
    entrypoint: sh
    args:
      - -c
      - 'echo //registry.npmjs.org/:_authToken=$${NPM_TOKEN} >> .npmrc'
    secretEnv:
      - NPM_TOKEN
  - name: node:10
    id: release
    waitFor:
      - authentication
    entrypoint: bash
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          npm publish || true
        fi
  - name: node:10
    id: release:dev
    waitFor:
      - release
    entrypoint: bash
    args:
      - '-c'
      - |
        npm version prerelease --preid="${SHORT_SHA}"
        npm publish --tag="dev"
secrets:
  - kmsKeyName: projects/com-ridedott-build/locations/global/keyRings/environments/cryptoKeys/production
    secretEnv:
      NPM_TOKEN: CiQAcJJb88NVYinGTE7S4JyNXX9b/y85JX3/0MJEIofzn0mvKmoSTQB9H8yZcgx/JyEO64gmVMI0rNS8qizf41Vn784rLCA1k97pmhNKy4WR5QcTv6yYdIhN2mg4pFgB24QbdJR/HqRDyAz/JIQLlnm+VTvs
